# https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# See supported Node.js release schedule at https://nodejs.org/en/about/releases/
env:
  NODE_VERSION: 20.x

jobs:
  test_pa11yci:
    name: Test with Pa11y-CI

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run start:detached
    - run: cat servor.log
    #- run: sleep 1
    - run: npm run test:pa11y-ci
    #-run: npm run kill

  test_cypress:
    name: Test with Cypress and Axe

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run start:detached
    - run: cat servor.log
    - run: npm run test:cypress

# End.
